import { GoogleGenAI } from '@google/genai';

const MODEL_NAME = 'gemini-2.5-flash-image';

const cleanBase64 = (base64Data: string): string => {
  return base64Data.split(',')[1];
};

const getClosestAspectRatio = (width: number, height: number): string => {
  const targetRatio = width / height;

  const supportedRatios = [
    { id: '1:1', value: 1.0 },
    { id: '3:4', value: 3 / 4 },
    { id: '4:3', value: 4 / 3 },
    { id: '9:16', value: 9 / 16 },
    { id: '16:9', value: 16 / 9 },
  ];

  const closest = supportedRatios.reduce((prev, curr) => {
    return Math.abs(curr.value - targetRatio) <
      Math.abs(prev.value - targetRatio)
      ? curr
      : prev;
  });

  return closest.id;
};

export const generateReupholstery = async (
  furnitureBase64: string,
  textureBase64: string,
  width: number,
  height: number
): Promise<string> => {
  try {
    const apiKey =
      import.meta.env.VITE_GEMINI_API_KEY ||
      localStorage.getItem('gemini_api_key');

    if (!apiKey) {
      throw new Error(
        'API Key not found. Please connect your Google AI Studio key.'
      );
    }

    const ai = new GoogleGenAI({ apiKey });

    const aspectRatio = getClosestAspectRatio(width, height);

    const prompt = `
      You are an expert digital upholsterer.
      Input 1: Original photo of furniture (Source).
      Input 2: Fabric texture (Target).
      
      Task: Re-upholster the furniture from Input 1 using the fabric from Input 2.
      
      CRITICAL CONSTRAINTS (MUST FOLLOW):
      1. **NO OUTPAINTING**: Do NOT expand the image boundaries. Do NOT add new content (walls, floor, sofa parts) that is not currently visible in Input 1.
      2. **PRESERVE CUT-OFFS**: If the furniture is cut off by the photo edge, it MUST remain cut off exactly the same way. Do not "complete" the object.
      3. **EXACT GEOMETRY**: The output must overlap perfectly with Input 1. Do not zoom, rotate, or change the camera angle.
      4. **ASPECT RATIO**: Output MUST have the exact same width/height ratio as Input 1. The target aspect ratio is set to ${aspectRatio}.
      
      UPHOLSTERY INSTRUCTIONS:
      5. **TEXTURE MAPPING**: Apply the texture from Input 2 realistically, following the folds, shadows, and curves of the original furniture.
      6. **PRESERVE DETAILS**: Keep tufting buttons, piping lines, and wood parts exactly as they are.
      7. **SURFACE ONLY**: Fix surface tears or stains on the fabric, but **DO NOT** alter the physical shape, padding volume, or structural elements (legs/frame) of the furniture.
      8. **LIGHTING & BACKGROUND**: Keep the original lighting and background pixels 100% identical.
      
      Output only the processed image.
    `;

    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            text: prompt,
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64(furnitureBase64),
            },
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64(textureBase64),
            },
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
        },
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;

    if (!parts) {
      throw new Error('No content generated by the model.');
    }

    const imagePart = parts.find((part) => part.inlineData);

    if (imagePart && imagePart.inlineData) {
      return `data:image/png;base64,${imagePart.inlineData.data}`;
    }

    throw new Error(
      'The model did not return an image. Try a different image or texture.'
    );
  } catch (error) {
    console.error('Gemini API Error:', error);
    throw error;
  }
};
